server:
  port: 8281

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Business Route: Forward /api/business/** to business-service
        - id: business-route
          uri: lb://business-service
          predicates:
            - Path=/api/business/**
          filters:
            - StripPrefix=2

        # Agent Route: Forward /rest/dark/v1/agent/** to python-agent
        - id: agent-route
          uri: lb://python-agent
          predicates:
            - Path=/rest/dark/v1/agent/**
          filters:
            - StripPrefix=0
        
        # LLM Proxy Route: Forward /v1/chat/** to OpenAI/DeepSeek
        - id: llm-proxy-route
          uri: https://api.openai.com
          predicates:
            - Path=/v1/chat/**
          filters:
            - name: AiBillingFilter

        # # Gemini Proxy Route
        # - id: gemini-route
        #   uri: https://generativelanguage.googleapis.com
        #   predicates:
        #     - Path=/gemini/**
        #   filters:
        #     - StripPrefix=1
        #     - AddRequestParameter=key, ${GEMINI_API_KEY}
  security:
    login-url: /oauth2/authorization/casdoor
    ignore:
      urls:
        - /api/public/**
    oauth2:
      client:
        registration:
          casdoor:
            provider: casdoor
            client-id: df6a2403823b8f014be5
            client-secret: 97d49db301cd4f5cbc37cd052917e7ee3b0c1c66
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          casdoor:
            # Casdoor 的 OIDC 发现地址 (Discovery Endpoint)
            issuer-uri: http://tao-lan.122577.xyz:8381
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
app:
  # 本地运行的 Angular 默认地址
  frontend-url: http://localhost:3000